s=original('or-higia*html')
s=replace(s,"const set=['house','star','heart'];","const set=['house','star','heart','kippah','shirt','cup','candle','siddur'].slice(0,[3,6,8][bLevel-1]);")
s=replace(s,'if(!sel)return;','if(!sel||sel.classList.contains("done")||d.classList.contains("filled"))return;')
s=replace(s,'if(done===items.length)m.textContent=win;','if(done===items.length){m.textContent=win;bAward(bCurrent);}')
s=replace(s,"if(f===set.length)m.textContent='מצאת את כל הזוגות!';","if(f===set.length){m.textContent='מצאת את כל הזוגות!';bAward('memory');}")
s=replace(s,"const tick=()=>{v=Math.min(100,v+1.4);","const tick=()=>{if(!b.isConnected||!modal.classList.contains('on')){clearInterval(t);return}v=Math.min(100,v+1.4);")
s=replace(s,"m.textContent='התינוק נרדם. חיכית — וזה עבד.';","m.textContent='התינוק נרדם. חיכית — וזה עבד.';bAward('patience');")
s=replace(s,"hb.addEventListener('pointerdown',on);","hb.addEventListener('pointerdown',on);hb.addEventListener('keydown',e=>{if(e.key===' '||e.key==='Enter')on(e)});hb.addEventListener('keyup',off);")
s=replace(s,"if(off===5){b.querySelector('#mn').style.opacity=1;","if(off===5){bAward('quiet');b.querySelector('#mn').style.opacity=1;")
s=replace(s,"window.addEventListener('pointerup',()=>down=false);","cv.addEventListener('pointerup',()=>down=false);cv.addEventListener('pointercancel',()=>down=false);cv.addEventListener('pointerleave',()=>down=false);")
# Add guards without replacing the original book navigation or content.
s=replace(s,'function openGame(id){','function openGame(id){bCurrent=id;bRoundLevel=bLevel;')
s=replace(s,'function show(dir){','function show(dir){if(typeof PlayUI!=="undefined")PlayUI.save("morash-book-page",p);')
s=replace(s," if(e.key==='ArrowLeft')goNext();"," if(modal.classList.contains('on')||document.querySelector('dialog[open]')||e.target.matches('input,select,textarea'))return;\n if(e.key==='ArrowLeft'){e.preventDefault();goNext();}")
s=replace(s," if(e.key==='ArrowRight')goPrev();"," if(e.key==='ArrowRight'){e.preventDefault();goPrev();}")
addon=r'''
let bRoundLevel=1,bLevel=PlayUI.read('morash-book-level',1),bCurrent='',bRecords=PlayUI.read('morash-book-stars',{});
const bBar=document.createElement('div');bBar.className='controlbar';bBar.innerHTML='<label>רמת משחק <select id="bookLevel" aria-label="רמת משחק"><option value="1">צעדים ראשונים · 3+</option><option value="2">מתקדמים · 6+</option><option value="3">אלופים · 9+</option></select></label><span class="mini-medal" id="bookStars"></span><button class="btn" id="bookBookmark">ממשיכים מהסימנייה</button>';document.querySelector('header').after(bBar);
const savedPage=PlayUI.read('morash-book-page',0);document.getElementById('bookBookmark').onclick=()=>{p=Math.min(PAGES.length-1,Math.max(0,savedPage));show();document.getElementById('pageImg').scrollIntoView({behavior:'smooth',block:'center'})};document.getElementById('bookLevel').value=bLevel;document.getElementById('bookLevel').onchange=e=>{bLevel=+e.target.value;PlayUI.save('morash-book-level',bLevel);bPaint()};
function bPaint(){document.getElementById('bookStars').textContent=Object.keys(bRecords).length*50+' נקודות · '+Object.keys(bRecords).length+' כוכבי משחק';document.querySelectorAll('.gbtn').forEach(b=>b.classList.toggle('b-earned',!!bRecords[b.dataset.g+'-'+bLevel]))}
function bAward(id){const key=id+'-'+bRoundLevel;if(!bRecords[key]){bRecords[key]=true;PlayUI.save('morash-book-stars',bRecords);PlayUI.celebrate();PlayUI.toast('כוכב חדש לאוסף · 50 נקודות')}bPaint()}
const bOriginalOpen=openGame;openGame=function(id){bOriginalOpen(id);if(id==='draw'){const bt=document.createElement('button');bt.className='btn';bt.textContent='שומרים את הציור';bt.onclick=()=>{const cv=document.getElementById('canvas'),out=document.createElement('canvas');out.width=cv.width;out.height=cv.height;const c=out.getContext('2d');c.fillStyle='white';c.fillRect(0,0,out.width,out.height);c.drawImage(cv,0,0);out.toBlob(blob=>{if(blob){PlayUI.download('הציור-שלי.png',blob);bAward('draw')}})};gb.append(bt)}if(id==='face'||id==='needs'){const bt=document.createElement('button');bt.className='btn';bt.textContent='סיימתי ליצור · שומרים כוכב';bt.onclick=()=>bAward(id);gb.append(bt)}gb.querySelectorAll('.drop').forEach(d=>{d.tabIndex=0;d.role='button';d.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();d.click()}}})};
const bQuiet=START.quiet;START.quiet=(b,m)=>{if(bLevel===1){bQuiet(b,m);return}const n=3,grid=Array(9).fill(false),solution=new Set();let won=false;function flip(i){for(const j of [i,i%n?i-1:-1,i%n<n-1?i+1:-1,i-n,i+n])if(j>=0&&j<9)grid[j]=!grid[j];if(solution.has(i))solution.delete(i);else solution.add(i)}for(let k=0;k<(bLevel===2?3:6);k++)flip(Math.floor(Math.random()*9));if(!grid.some(Boolean))flip(4);b.innerHTML='<p class="muted">כל לחיצה משנה גם את האורות הצמודים. נסו לכבות את כולם!</p><div class="b-lights"></div><button class="btn" id="bHint">רמז לצעד הבא</button>';function paint(){b.querySelector('.b-lights').innerHTML=grid.map((v,i)=>'<button data-light="'+i+'" aria-label="אור '+(i+1)+'" aria-pressed="'+v+'" style="background:'+(v?'#f4cf70':'#335964')+'">'+(v?'☀':'·')+'</button>').join('')}paint();b.querySelector('.b-lights').onclick=e=>{const bt=e.target.closest('[data-light]');if(!bt||won)return;flip(+bt.dataset.light);paint();if(!grid.some(Boolean)){won=true;m.textContent='הבית נרדם. לילה טוב.';bAward('quiet')}};b.querySelector('#bHint').onclick=()=>{if(won)return;const i=[...solution][0],bt=b.querySelector('[data-light="'+i+'"]');if(bt){bt.style.outline='4px solid #e58572';bt.focus()}}};
document.addEventListener('keydown',e=>{if(modal.classList.contains('on')&&e.key==='Escape')modal.classList.remove('on')});bPaint();
'''
css=r'''.hero{display:block!important}.mem{grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:10px!important}.mem .card{background:#358f8b;border-radius:18px;box-shadow:0 5px 0 #196965}.mem .card.up{background:#f5d385}.mem .card.matched{background:#cce4d5}.gbtn{border-radius:23px!important;box-shadow:0 7px 0 #e4d7bd60;position:relative}.gbtn.b-earned:after{content:'★';position:absolute;top:4px;left:10px;color:#ba8826}.b-lights{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:18px auto;max-width:390px}.b-lights button{height:84px;border:5px solid #fff5db;border-radius:20px;color:#fff9e9;font-size:35px}.modal .box{border-radius:28px}#pageImg{border-radius:12px}.controlbar .btn{font-size:13px;padding:8px 12px}@media(max-width:600px){.mem .card{min-width:0}.controlbar{margin:10px}}
'''
upgrade(s,'b-story.html',addon,css)
