s=original('masa-hamitzvot*html')
# Draw tzitzit over the trousers so the existing modest character details remain visible.
s=s.replace('<path d="M21 49v5M25 49v5M35 49v5M39 49v5" stroke="#fff" stroke-width="1.4"/>','')
s=s.replace('<ellipse cx="24" cy="77"', '<path d="M20 48l-1 10m3-10v11m16-11 1 10m-3-10v11" stroke="#fff9ec" stroke-width="1.5" fill="none" stroke-linecap="round"/><ellipse cx="24" cy="77"')
s=replace(s,'function nextTurn(){G.turn=(G.turn+1)%G.players.length;busy=false;renderGame();checkWin();}', 'function nextTurn(){G.turn=(G.turn+1)%G.players.length;busy=false;dSave();renderGame();checkWin();}')
s=replace(s,'buildBoard();renderGame();\n};','buildBoard();renderGame();dSave();\n};')
s=replace(s,'function cardMitzva(p){','function cardMitzva(p,chosen){')
s=replace(s,'const m=pool.length?rnd(pool):rnd(MITZVOT);','const m=chosen||(pool.length?rnd(pool):rnd(MITZVOT));')
s=replace(s,'$("#again").onclick=()=>location.reload();','$("#again").onclick=()=>{localStorage.removeItem("morash-city-v1");location.reload()};')
s=replace(s,'const left=Math.max(0,8000-(now-t0));','if(document.hidden){t0+=Math.max(0,now-lastHidden);lastHidden=now;catchRAF=requestAnimationFrame(frame);return}if(now-lastHidden>250)t0+=now-lastHidden;lastHidden=now;const left=Math.max(0,dDuration-(now-t0));')
s=replace(s,'const dt=Math.min(50,now-last);last=now;','const dt=Math.min(50,now-last);last=now;')
s=replace(s,'(left/8000*100)','(left/dDuration*100)')
s=replace(s,'const p=cur(),area=$("#catchArea");','const p=cur(),area=$("#catchArea");const dDuration=[12000,10000,8000][dLevel-1];let lastHidden=performance.now();')
addon=r'''
let dLevel=PlayUI.read('morash-city-level',1);const dSnapshot=PlayUI.read('morash-city-v1',null);
const dBar=document.createElement('div');dBar.className='controlbar';dBar.innerHTML='<label>קצב המשחק <select id="cityLevel" aria-label="קצב המשחק"><option value="1">נינוח · 4+</option><option value="2">זריז · 7+</option><option value="3">מהיר · 10+</option></select></label><span class="mini-medal" id="citySaved">בונים עיר, בניין אחרי בניין</span>';document.getElementById('setup').prepend(dBar);document.getElementById('cityLevel').value=dLevel;document.getElementById('cityLevel').onchange=e=>{dLevel=+e.target.value;PlayUI.save('morash-city-level',dLevel)};
function dSave(){if(G.started){PlayUI.save('morash-city-v1',G);document.getElementById('citySaved').textContent='העיר נשמרה · אפשר לחזור ולהמשיך'}}
if(dSnapshot&&Array.isArray(dSnapshot.players)&&dSnapshot.players.length&&dSnapshot.city){const resume=document.createElement('button');resume.className='bigbtn green';resume.textContent='ממשיכים בעיר שבנינו';resume.onclick=()=>{G=dSnapshot;busy=false;document.getElementById('setup').classList.add('hidden');document.getElementById('game').classList.remove('hidden');document.getElementById('cityBtn').classList.remove('hidden');document.getElementById('albumBtn').classList.remove('hidden');buildBoard();renderGame();checkWin()};dBar.append(resume)}
const dWorkshop=document.createElement('button');dWorkshop.className='bigbtn';dWorkshop.textContent='בוחרים בניין';dWorkshop.onclick=()=>{if(busy||cur().ai){PlayUI.toast('מסיימים את התור הנוכחי ואז בוחרים בניין');return}busy=true;cardMitzva(cur())};document.querySelector('.actionrow').append(dWorkshop);
const dOriginalMission=cardMitzva;cardMitzva=function(p,chosen){if(chosen||p.ai){dOriginalMission(p,chosen);return}const available=PlayUI.shuffle(MITZVOT.filter(m=>!cityOf(p).done[m.id])).slice(0,3);if(!available.length){dOriginalMission(p);return}showSheet('<div class="kicker">תורכם לבחור!</div><h3>מה בונים עכשיו?</h3><div class="d-build-choices">'+available.map((m,i)=>'<button class="d-build-choice" data-build="'+i+'"><span class="d-crane">'+ic('crane',42)+'</span><b>'+K(m.t,m.n)+'</b><span class="d-gain">+'+m.p+'</span></button>').join('')+'</div>');document.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>dOriginalMission(p,available[+b.dataset.build]))};
const dOldBuild=buildMitzva;buildMitzva=function(p,m){dOldBuild(p,m);const count=cityList(cityOf(p)).length;if(count&&count%5===0){const note=document.createElement('div');note.className='d-milestone';note.textContent='✦ '+count+' בניינים בעיר שלכם!';document.getElementById('engineBox')?.append(note);PlayUI.toast(count+' בניינים! העיר שלכם הולכת וגדלה')}};
'''
css=r''':root{--pink:#e98274;--sky:#379a9b;--green:#448d76;--gold:#e8ba58}.bigbtn{border-radius:19px!important;box-shadow:0 5px 0 #23473e22!important}.opt,.playerrow{border-radius:20px!important}.d-build-choices{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:24px 0}.d-build-choice{background:#fff9eb;border:2px solid #dcdfc8;border-radius:20px;padding:18px 12px;display:grid;gap:12px;justify-items:center;color:#315850;font:inherit}.d-build-choice:hover{background:#deeee3;transform:translateY(-5px)}.d-build-choice b{font-size:15px;line-height:1.6}.d-gain{background:#f5d688;border-radius:30px;padding:5px 17px;font-weight:800}.d-milestone{padding:12px;border-radius:15px;background:#e4efd9;color:#386e59}.boardwrap{filter:drop-shadow(0 18px 35px #375c4610)}.controlbar{font-size:13px}.controlbar select{font-size:13px}@media(max-width:580px){.d-build-choices{grid-template-columns:1fr}.d-build-choice{grid-template-columns:auto 1fr auto;align-items:center;text-align:right;padding:12px}.controlbar{margin:12px 0}}
'''
upgrade(s,'d-mitzvot.html',addon,css)
