s=original('masa-bazman*html')
s=replace(s,'function afterMini(){','function afterMini(){')
s=replace(s,'if(step>=N) finish(); else renderStep();','eSave();if(step>=N) finish(); else renderStep();')
s=replace(s,'function startGame(){','function startGame(){eRunMode=document.getElementById("timeMode").value;')
s=replace(s,'buildDots();clearHouse();renderStep();','buildDots();clearHouse();renderStep();eSave();')
s=replace(s,'renderTurn();paintSky();deal();','renderTurn();paintSky();deal();if(eRunMode==="hands"){document.getElementById("choices").style.display="none";eHands()}') if 'id="choices"' in s else s
addon=r'''
let eRunMode='classic';const eSnapshot=PlayUI.read('morash-time-v1',null);
const eBar=document.createElement('div');eBar.className='controlbar';eBar.innerHTML='<label>איך משחקים? <select id="timeMode" aria-label="סגנון מסע"><option value="classic">חידות ואתגרים</option><option value="hands">מסע של עשייה</option></select></label><span class="mini-medal">12 תחנות · בונים יום שלם</span>';document.getElementById('playBtn').before(eBar);
function eSave(){PlayUI.save('morash-time-v1',{step,scores,turn,players,level,nikud,mode:eRunMode})}
function eHands(){const existing=document.getElementById('eHands');if(existing)existing.remove();const row=document.createElement('div');row.id='eHands';row.innerHTML='<div class="e-current"><span>'+EVENTS[step].ic+'</span><h3>'+L(EVENTS[step].t)+'</h3><p>'+L(EVENTS[step].d)+'</p><button class="btn primary" id="eAction">משחקים בתחנה הזאת</button></div>';document.getElementById('askText').after(row);document.getElementById('eAction').onclick=()=>{if(busy)return;busy=true;scores[turn]++;renderTurn();runMini(step)}}
const eOriginalMini=runMini;runMini=function(i){eOriginalMini(i);let taps=0;const total=[4,6,8][level-1],b=document.createElement('button');b.className='btn';b.style.cssText='margin:12px auto;display:block';b.innerHTML='אפשר גם בלחיצות · <bdi>0 / '+total+'</bdi>';b.onclick=()=>{if(miniDone)return;taps++;bar(taps/total*100);b.innerHTML='עוד צעד · <bdi>'+taps+' / '+total+'</bdi>';if(taps>=total){b.disabled=true;miniFinish()}};b.id='eTapAlternative';document.getElementById('eTapAlternative')?.remove();document.querySelector('#mini .mbar').after(b);b.addEventListener('pointerdown',e=>e.stopPropagation())};
const eOriginalRender=renderStep;renderStep=function(){document.getElementById('eHands')?.remove();document.getElementById('hand').style.display='';document.getElementById('fb').style.display='';eOriginalRender();if(eRunMode==='hands'){document.getElementById('hand').style.display='none';document.getElementById('fb').style.display='none';if(!document.getElementById('eHands'))eHands()}};
if(eSnapshot&&Number.isInteger(eSnapshot.step)&&eSnapshot.step>0&&eSnapshot.step<N){const b=document.createElement('button');b.className='btn';b.textContent='ממשיכים מתחנה '+(eSnapshot.step+1);b.onclick=()=>{step=eSnapshot.step;scores=eSnapshot.scores;turn=eSnapshot.turn;players=eSnapshot.players;level=eSnapshot.level;nikud=eSnapshot.nikud;eRunMode=eSnapshot.mode||'classic';document.getElementById('timeMode').value=eRunMode;$('startScreen').classList.add('off');$('finale').classList.remove('on');buildDots();clearHouse();for(let i=0;i<step;i++)addHouseItem(i);applyText();renderStep()};eBar.append(b)}
'''
css=r'''.e-current{background:#fff9e9;border:2px solid #dce6cf;border-radius:24px;padding:22px;text-align:center;max-width:460px;margin:16px auto}.e-current>span{font-size:55px}.e-current h3{font-size:24px;margin:8px 0}.e-current p{color:#526d61;font-size:16px}.controlbar{font-size:14px}.marea{border-radius:24px!important}.choice{border-radius:22px!important;box-shadow:0 7px 0 #b3c9b433}.card{border-radius:24px}.controlbar select{font-size:13px}.btn.primary{color:white}
'''
upgrade(s,'e-time.html',addon,css)
