s=original('חלק י.html')
s=replace(s,'מצב הדגמה ← קפצי ליום הבא','כרטיס נוסף להיום')
s=replace(s,"$('#next').onclick=()=>{S.day++;S.today=null;$('#dm').textContent='יום '+S.day;go('mood');toast('בוקר חדש')};","$('#next').onclick=()=>{S.today=null;go('mood');toast('בוחרים רגע נוסף להיום')};")
addon=r'''
const jKey='morash-meravach-v1';const jNow=()=>{const d=new Date();return Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())};
let jData=PlayUI.read(jKey,null),jStart=jData?.started||jNow(),jDate=jData?.date||jNow();
if(jData&&jData.state){const v=jData.state;S.today=Number.isInteger(v.today)&&v.today>=0&&v.today<CARDS.length?v.today:null;S.done=v.done||{};S.saved=v.saved||{};S.couple=v.couple||{};S.used=new Set(Array.isArray(v.used)?v.used:[])}
function jRefresh(){const now=jNow();S.day=Math.max(1,Math.floor((now-jStart)/86400000)+1);if(jDate!==now){jDate=now;S.today=null;go('mood')}$('#dm').textContent='יום '+S.day}
function jSave(){PlayUI.save(jKey,{started:jStart,date:jDate,state:{...S,used:[...S.used]}})}
jRefresh();if(S.today!==null){drawCard();go('card')}window.addEventListener('focus',()=>{jRefresh();jSave()});document.addEventListener('click',()=>queueMicrotask(jSave));document.addEventListener('input',()=>queueMicrotask(jSave));
drawCouple=function(i){const c=CARDS[i],qs=QS[c.c],q=qs[i%qs.length],st=S.couple[i]||(S.couple[i]={mine:'',partner:''});$('#coupleBox').innerHTML='<h2 class="title">שאלת ערב</h2><p class="eyebrow">כל אחד כותב לעצמו, ובערב קוראים יחד. לא מבחן, התחלה של שיחה.</p><div class="q-card"><small>מתוך "'+PlayUI.escape(c.t)+'"</small><div class="q">'+PlayUI.escape(q)+'</div></div><div class="half"><small>אני</small><textarea id="ta" placeholder="מה שעולה, במילים שלך"></textarea></div><div class="half"><small>הוא</small><textarea id="partner" placeholder="אפשר לכתוב יחד במכשיר הזה"></textarea></div><p class="muted">התשובות נשמרות רק במכשיר הזה. כפתור השיתוף משתף את השאלה בלבד.</p><button class="btn wide plum" id="snd">לשמור ולשתף את השאלה</button><button class="btn wide" id="bk">חזרה לכרטיס</button>';$('#ta').value=st.mine||'';$('#partner').value=st.partner||'';$('#ta').oninput=e=>{st.mine=e.target.value;st.sent=!!(st.mine.trim()&&(st.partner||'').trim());jSave()};$('#partner').oninput=e=>{st.partner=e.target.value;st.sent=!!(st.mine.trim()&&st.partner.trim());jSave()};$('#snd').onclick=async()=>{jSave();const text=q;try{if(navigator.share){await navigator.share({text});toast('השיתוף הושלם')}else{await navigator.clipboard.writeText(text);toast('השאלה הועתקה. אפשר להדביק בהודעה')}}catch(e){if(e.name!=='AbortError')toast('התשובות נשמרו. אפשר להעתיק את השאלה ידנית')}};$('#bk').onclick=()=>go('card')};
const jNote=document.createElement('div');jNote.className='j-persistence';jNote.textContent='הרגעים והכרטיסים ששמרת מחכים לך במכשיר הזה';document.querySelector('header').after(jNote);
const jExport=document.createElement('button');jExport.className='btn';jExport.textContent='הורדת המחברת שלי';jExport.onclick=()=>{let lines=['מרווח · המחברת שלי',''];for(const [key,st]of Object.entries(S.couple)){const i=Number(key);if(!CARDS[i])continue;const c=CARDS[i];lines.push(c.t,QS[c.c][i%QS[c.c].length],'אני: '+(st.mine||''),'הוא: '+(st.partner||''),'')}for(const key of Object.keys(S.saved)){if(!S.saved[key]||!CARDS[key])continue;const c=CARDS[key];lines.push('כרטיס שמור: '+c.t,c.i,c.m,'')}PlayUI.download('המחברת-שלי.txt',new Blob(['\ufeff'+lines.join('\n')],{type:'text/plain;charset=utf-8'}))};document.getElementById('s-album')?.append(jExport);jSave();
'''
css=r'''.j-persistence{font-size:11px;text-align:center;color:#8a8579;padding:10px 15px}.demo{padding:8px 20px!important;background:#f5ebdf!important}.demo button{color:#786f60!important}.app{box-shadow:0 20px 70px #574a3510}.mood-btn{border-radius:19px!important;box-shadow:0 4px 15px #644c3c05}.card{border-radius:26px!important}.btn.fill,.btn.plum{background:#786378;color:white;border:0}.btn{box-shadow:none;font-size:14px}.half textarea{width:100%;min-height:105px}.tag{font-size:12px}
'''
upgrade(s,'j-meravach.html',addon,css)
