"""Generate the owner's review checklist alongside the delivery files."""
items={
'a':('צובעים ומרכיבים!','עדכון 24.9: איורים חדשים ומתוקנים, חיפוש חפצים, זיכרון משופר ותיקון חוברת, שמירה והדפסה.','בדקי את 19 הדפים, את ארבעת המשחקים ואת ההדפסה בטלפון ובמדפסת שלך.'),
'b':('אור הגיע אלינו','ניווט נקי, הבחנה בין תמונת הספר לקריאה בטקסט ותיקון החפיפה בכפתור הסגירה.','דפדפי בספר, נסי את שמונה הפעילויות והגיהי את התמלול והניקוד.'),
'c':('בית המצוות','הוראה לפני הבחירה בטלפון ורשימת בחירה חלופית סגורה, למניעת כפתורים כפולים במסך.','נסי את חמשת האתגרים, החידות ואיסוף האותיות.'),
'd':('מסע המצוות','הקדמה, הסבר לתור הראשון, הבחנה בין המסלול הרגיל למשימת בנייה וחזרה לתפריט.','נסי בחירת משתתפים, תור איסוף, בניית עיר והמשך משחק שמור.'),
'e':('מסע בזמן','בקרי קריאה אחידים, הסבר לשני המסלולים וחזרה מהפעילות לתחנה.','נסי חידות ואתגרים, מסע עשייה וחלופת הלחיצות.'),
'f':('מטבח השבת','תצוגת טלפון קומפקטית, הוראות לאצבע ולעכבר/מקלדת ויציאה ששומרת את השלב.','הכיני חלה, נסי גרירה ולישה, וצאי וחזרי באמצע.'),
'g':('תעלומת המתנה','הוסרה תמונת פתיחה כפולה ומונה העדויות מוצג בסדר ברור.','קראי, חפשי ארבעה רמזים, סווגי עדויות ובדקי את הפתרון.'),
'h':('כרטיס מכל הלב','גישה לתצוגה מוגדלת מתוך כלי העריכה בטלפון, מעבר ישיר לציור ואזורי מגע גדולים יותר.','בחרי ברכה, חתמי, קשטי והורידי תמונה; בדקי גם ביטול ומחיקה.'),
'i':('צעדים ראשונים','הבהרה שאפשר להשלים פרטים בהמשך, פתיחה מותאמת לאמא ובדיקת גיבוי ושחזור.','צרי מפה, סמני משימה, הוסיפי הערה ובדקי את הנוסחים והקישורים.'),
'j':('מרווח','בחירת כרטיס נוסף הועברה לאחר הכרטיס ונשמר רצף הפתיחה.','בחרי הרגשה, שמרי כרטיס, כתבי שאלת ערב והורידי מחברת.')}
for gid,copy in editorial.items():
    old=items[gid];items[gid]=(copy['title'],{'a':'עודכנו הכותרת, ההסבר ותיאור משחקי שעות הפנאי לפי הערות העריכה.','b':'עודכנו שמות הפעילויות וההוראות. כפתור הסגירה נשאר נגיש גם בגלילה.','c':'עודכנו הכותרת וההוראות; משחק המספרים מסודר בשורה מימין לשמאל.'}[gid],old[2])
cards=[]
for g in data:
    gid=g['id'];title,change,check=items[gid]
    cards.append(f'''<article class="review-card"><img src="ערכת-תצוגה-לאתר/{gid}-cover.webp" alt="" loading="lazy" width="1536" height="1024"><div class="review-content"><h2>{title}</h2><p>{change}</p><a class="button launch" href="https://bracha-games-review.marpad990579.chatgpt.site/workspace?game={gid}" target="_blank" rel="noopener">משחק, תיקונים והחלטות הכותבת ↗</a><details><summary>מה כדאי לבדוק?</summary><p>{check}</p></details><label for="status-{gid}">המצב שלי</label><select id="status-{gid}"><option value="todo">עוד לא עברתי</option><option value="notes">יש לי תיקונים</option><option value="approved">מוכן מבחינתי</option></select><label for="note-{gid}">טיוטת הערה על המשחק</label><textarea id="note-{gid}" rows="4" placeholder="באיזה מסך? מה קרה? מה תרצי לשנות? צייני אם בטלפון או במחשב."></textarea><button class="button send-general" data-game="{gid}">פרסום ההערה לכולן</button></div></article>''')
body='''<h1>בודקות, משחקות וכותבות תיקונים.</h1><section class="reviewer-details"><h2>החלטות הכותבת ותיקונים</h2><a class="button launch" href="https://bracha-games-review.marpad990579.chatgpt.site/workspace">משחקים ומחליטים — סביבת הכותבת</a> <a class="button" href="https://bracha-games-review.marpad990579.chatgpt.site/fixes">סיכום התיקונים והחלוקה</a> <a class="button" href="https://bracha-games-review.marpad990579.chatgpt.site/downloads/corrected-games.zip" download>הורדת המשחקים המתוקנים</a></section><p class="lead">גרסת בדיקה · 16.9.2026 · עשרת חלקי הבאת ברכה</p><p>פותחים כל חלק, משחקים וכותבים כאן את התיקונים האחרונים. המשחק נפתח בלשונית נפרדת, כך שהרשימה נשארת כאן.</p><section class="reviewer-details"><h2>פרטי הבדיקה שלך</h2><label for="reviewerName">שם הבודקת</label><input id="reviewerName" autocomplete="name" maxlength="100" placeholder="כדי שנדע ממי הגיעו התיקונים"><label for="reviewDevice">איפה בדקת?</label><select id="reviewDevice"><option value="">בחרי מכשיר</option><option>טלפון</option><option>מחשב</option><option>טלפון ומחשב</option><option>טאבלט</option></select><label for="generalNotes">הערות כלליות על האתר</label><textarea id="generalNotes" rows="3" placeholder="התרשמות כללית, ניווט, עיצוב או משהו שחסר"></textarea><button class="button send-general" data-game="general">פרסום הערה כללית לכולן</button></section><div class="review-toolbar"><strong id="progress" aria-live="polite"></strong><span id="saveStatus" role="status">הטיוטות נשמרות אוטומטית במכשיר ומגובות לענן. פרסום ברשימה המשותפת מציג אותן לכולן.</span></div><div class="note"><b>מה כדאי לבדוק</b><p>עברי גם בטלפון אמיתי ובמחשב. בדיקות הטלפון האוטומטיות בוצעו בהדמיית מסך ומגע ב־Edge, ואינן בדיקה של מכשיר iPhone או Android פיזי. תמלול הספר והניקוד החדש מחכים להגהה שלך.</p></div><div class="docs"><a href="התחילו-כאן.html">כל קובצי המסירה</a><a href="מסמכים/סיכום-בדיקה-סופית.html">מה תוקן ומה נבדק</a><a href="טקסטים/כל-הטקסטים.html">הטקסטים להגהה</a></div><section class="reviewer-details"><h2>הערות בנקודה המדויקת במשחק</h2><p>פתחי משחק, לחצי על ״הוספת הערה״ ואז על התמונה, הכפתור או האזור שעליו תרצי להעיר. אפשר להמשיך לשחק ולהוסיף סימונים במסכים נוספים.</p><p id="pointCount" role="status"></p><button class="button" id="viewPointNotes">כל ההערות והתגובות של כולן</button> <button class="button" id="downloadPointNotes">הורדת מסמך גיבוי לשליחה</button></section><div class="review-grid">'''+''.join(cards)+'</div>'
css='''<style>.review-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}.review-card{border:1px solid #dce1d4;border-radius:24px;overflow:hidden;background:#fffdf8}.review-card>img{width:100%;height:auto;aspect-ratio:2;object-fit:cover}.review-content{padding:24px}.review-content h2{margin:10px 0;font-size:27px}.review-content p{font-size:15px}.reviewer-details{padding:24px;background:#fffdf8;border:1px solid #dce1d4;border-radius:20px;margin:24px 0}.reviewer-details label,.review-content label{display:block;font-weight:bold;margin:16px 0 6px}.reviewer-details input,.reviewer-details select,.reviewer-details textarea,.review-content textarea,.review-content select{width:100%;padding:12px;border:1px solid #b9cbc0;border-radius:12px;background:white;font:16px/1.7 Arial,sans-serif;color:#264447}.review-content textarea{resize:vertical}.review-content summary{font-size:16px}.launch{background:#176d69!important;color:white!important}.review-toolbar{display:flex;flex-wrap:wrap;align-items:center;gap:14px;background:#e3eee5;padding:18px;border-radius:18px}.review-toolbar span{font-size:13px;flex-basis:100%}.review-card:has(option[value=approved]:checked){border:2px solid #438779}.review-card:has(option[value=notes]:checked){border:2px solid #c98a52}a:focus-visible,button:focus-visible,summary:focus-visible,select:focus-visible,textarea:focus-visible{outline:3px solid #aa612c;outline-offset:3px}@media(max-width:700px){.review-grid{grid-template-columns:1fr}.review-content{padding:20px}h1{font-size:32px}.review-toolbar .button{width:100%}}</style>'''
script='<script>'+(DEV/'draft-backup.js').read_text(encoding='utf-8')+'</script><script>'+(DEV/'reviewer-notes.js').read_text(encoding='utf-8').replace('__NAMES__',json.dumps({k:v[0] for k,v in items.items()},ensure_ascii=False))+'</script><script>'+(DEV/'point-review.js').read_text(encoding='utf-8')+'</script>'

(FINAL/'בדיקה-סופית.html').write_text(page('בדיקת המשחקים וכתיבת תיקונים · הבאת ברכה',body,css.removeprefix('<style>').removesuffix('</style>'))+script,encoding='utf-8')
report='<h1>סיכום בדיקה ותיקונים</h1><p class="lead">16.9.2026 · גרסה למעבר שלך לפני פרסום</p><div class="docs"><a href="../בדיקה-סופית.html">לרשימת הבדיקה וההערות</a></div>'
for gid,(title,change,check) in items.items():report+='<div class="entry"><h2>'+title+'</h2><p>'+change+'</p></div>'
report+='<h2>בדיקות</h2><p>פתיחה ופריסה לכל עשרת החלקים ברוחב 320, 390 ו־1440 פיקסלים; פעילויות במחשב ובתצוגת טלפון; שגיאות JavaScript, תמונות חסרות וגלילה אופקית; תפקוד ושמירה; השוואת 30 אוספי תוכן למקור; קישורים ואריזות ZIP. פירוט התוצאות בפועל מצורף בקובצי JSON.</p><h2>למעבר שלך</h2><p>הגהת הספר והניקוד, התאמת הקושי לקהל ובדיקה בטלפון פיזי. הדפסה ושיתוף לאפליקציות אחרות דורשים מעבר במכשיר שבו תשתמשי. הגרסה מיועדת לסבב בדיקה ומשוב; הגהת התוכן ובדיקה בטלפון פיזי עדיין נדרשות.</p>'
(DOCS/'סיכום-בדיקה-סופית.html').write_text(page('סיכום בדיקה סופית',report),encoding='utf-8')
for filename in ['landing-audit.json','flow-audit.json','deep-audit.json','final-audit.json','shared-review-audit.json','live-review-audit.json','editorial-audit.json']:
    src=DEV/'review-evidence'/filename
    if src.exists():shutil.copy2(src,DOCS/('review-'+filename))
p=FINAL/'התחילו-כאן.html';s=p.read_text(encoding='utf-8');s=s.replace('<main>','<main><section class="reviewer-details"><h2>בודקות ומחליטות בתוך המשחק</h2><a class="button" href="https://bracha-games-review.marpad990579.chatgpt.site/workspace">פתיחת סביבת הכותבת</a></section><div class="note"><b>בודקות את המשחקים?</b><p>פתחי את דף הבדיקה, סמני פריטים במשחק וכתבי הערות ברשימה המשותפת.</p><a class="button" href="בדיקה-סופית.html">מעבר למשחקים ולרשימת התיקונים</a></div>',1);p.write_text(s,encoding='utf-8')
release=json.loads((DEV/'a-release.json').read_text(encoding='utf-8'))
(DOCS/'עדכון-מתחם-הצביעה.json').write_text(json.dumps(release,ensure_ascii=False,indent=2),encoding='utf-8')
(DOCS/'עדכון-מתחם-הצביעה.html').write_text(page('עדכון מתחם הצביעה','<h1>צובעים ומרכיבים! — עדכון 24.9.2026</h1><ul>'+''.join('<li>'+html.escape(t)+'</li>' for t in release['changes'])+'</ul><p>'+html.escape(release['limitation'])+'</p><a class="button" href="../משחקים/a-coloring/index.html">פתיחת המתחם</a>'),encoding='utf-8')
for evidence in ['a-final-audit.json','a-print-audit.json','a-print-pdf-audit.json']:
    shutil.copy2(DEV/'review-evidence'/evidence,DOCS/evidence)
manifest={str(p.relative_to(FINAL)):hashlib.sha256(p.read_bytes()).hexdigest() for p in FINAL.rglob('*') if p.is_file() and p.name!='manifest-sha256.json'}
(DOCS/'manifest-sha256.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2),encoding='utf-8')
