const fs=require('fs'),path=require('path'),assert=require('assert');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out=path.join(__dirname,'review-evidence');
(async()=>{
const browser=await chromium.launch({headless:true,channel:'msedge'}),context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,acceptDownloads:true,reducedMotion:'reduce'}),results=process.env.ONLY?JSON.parse(fs.readFileSync(path.join(out,'deep-audit.json'),'utf8')):[];
async function test(id,file,run){if(process.env.ONLY&&!process.env.ONLY.split(',').includes(id))return;const prev=results.findIndex(r=>r.id===id);if(prev>=0)results.splice(prev,1);const p=await context.newPage(),errors=[];p.setDefaultTimeout(8000);p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());try{await p.goto('http://127.0.0.1:8765/upgraded/'+file);await run(p);assert.deepEqual(errors,[]);results.push({id,passed:true,errors});console.log(id+' PASS')}catch(e){results.push({id,passed:false,error:e.message,errors});console.log(id+' FAIL '+e.message)}await p.screenshot({path:path.join(out,id+'-deep.png'),fullPage:true});await p.close();fs.writeFileSync(path.join(out,'deep-audit.json'),JSON.stringify(results,null,2))}
await test('a','a-coloring/index.html',async p=>{
 await p.locator('[data-go=games]').click();await p.locator('[data-game=memory]').click();
 const ids=await p.locator('.mem').evaluateAll(els=>[...new Set(els.map(e=>e.dataset.id))]);
 for(const id of ids){const cards=p.locator(`.mem[data-id="${id}"]`);await cards.nth(0).click();await cards.nth(1).click();await p.waitForTimeout(480)}
 assert.equal(await p.locator('#pr').innerText(),String(ids.length));
 await p.locator('[data-close=gpanel]').click();await p.locator('[data-game=puzzle]').click();
 for(let n=0;n<8;n++){const tiles=await p.locator('#pzb .pz').evaluateAll(es=>es.map(e=>({i:+e.dataset.i,x:parseFloat(e.style.backgroundPositionX),y:parseFloat(e.style.backgroundPositionY),ok:e.classList.contains('ok')})));if(tiles.every(t=>t.ok))break;const t=tiles.find(t=>!t.ok),target=(t.y===100?2:0)+(t.x===100?1:0);await p.locator(`#pzb [data-i="${t.i}"]`).click();await p.locator(`#pzb [data-i="${target}"]`).click()}
 assert((await p.locator('#pzs').innerText()).includes('הצלחתם'));
 await p.locator('[data-close=gpanel]').click();await p.locator('[data-game=number]').click();await p.locator('#nArt').waitFor();assert(await p.locator('.num-sw').count()>0);
 await p.locator('[data-close=gpanel]').click();await p.locator('[data-game=match]').click();for(let i=0;i<8;i++){const target=await p.locator('.match-target').getAttribute('src');const id=target.match(/(\d+)/g).at(-1);const match=p.locator(`[data-mid="${Number(id)}"]`);if(await match.count())await match.click();else{const answer=await p.evaluate(()=>{const img=document.querySelector('.match-target').getAttribute('src');return [...document.querySelectorAll('[data-mid]')].find(b=>cthumb(+b.dataset.mid)===img)?.dataset.mid});await p.locator(`[data-mid="${answer}"]`).click()}await p.waitForTimeout(800)}assert(await p.locator('#magain').isVisible());
});
await test('b','b-story.html',async p=>{
 await p.locator('#next').click();await p.locator('#bookRead').click();await p.locator('#bookReaderNext').click();assert((await p.locator('#bookReaderCount').innerText()).startsWith('3'));await p.locator('#bookReaderClose').click();
 await p.locator('[data-g=memory]').click();const ids=await p.locator('.mem .card').evaluateAll(es=>[...new Set(es.map(e=>e.dataset.n))]);for(const id of ids){await p.locator(`.mem [data-n=${id}]`).nth(0).click();await p.locator(`.mem [data-n=${id}]`).nth(1).click()}assert.equal(await p.locator('.mem .matched').count(),ids.length*2);await p.locator('#close').click();
 for(const id of ['patience','dress','face','table','quiet','needs','draw']){await p.locator(`[data-g=${id}]`).click();assert(await p.locator('#gb').isVisible());assert((await p.locator('#gb').innerHTML()).length>50);await p.locator('#close').click()}
 await p.reload();await p.locator('#bookBookmark').click();assert((await p.locator('#count').innerText()).includes('3'));
});
await test('c','beit-hamitzvot.html',async p=>{
 for(let i=0;i<5;i++){await p.locator(`.hotspot[data-open="${i}"]`).click();assert(await p.locator('#play').isVisible());await p.locator('#close').click()}
 await p.locator('.hotspot').first().click();for(let i=0;i<8;i++)await p.locator('.target').first().click({force:true});await p.locator('[data-answer]').first().waitFor();const id=await p.evaluate(()=>OBJECTS[0].id);await p.locator(`[data-answer="${id}"]`).click();await p.locator('#back').click();await p.reload();assert.equal(await p.locator('#score').innerText(),'100');
});
await test('d','d-mitzvot.html',async p=>{
 await p.locator('#startGame').click();await p.locator('.review-workshop').click();await p.locator('[data-build]').first().waitFor();assert.equal(await p.locator('[data-build]').count(),3);
 // Exercise a complete reading mission deterministically; the mission itself remains the original.
 await p.evaluate(()=>cardMitzva(cur(),MITZVOT.find(m=>m.eng==='read')));await p.waitForTimeout(600);const buttons=await p.locator('#engineBox button').count();assert(buttons>0);await p.locator('#engineBox button').last().click({timeout:40000});await p.locator('#ok').waitFor({timeout:20000});await p.locator('#ok').click();assert(await p.evaluate(()=>Object.keys(cityOf(G.players[0]).done).length>0));
});
await test('e','e-time.html',async p=>{
 await p.locator('#timeMode').selectOption('hands');await p.locator('#playBtn').click();await p.locator('#eAction').click();await p.locator('#timeCloseActivity').click();assert.equal(await p.evaluate(()=>scores[turn]),0);
 for(let i=0;i<12;i++){await p.locator('#eAction').click();for(let k=0;k<4;k++)await p.locator('#eTapAlternative').click();await p.waitForTimeout(600)}assert.equal(await p.evaluate(()=>step),12);await p.waitForFunction(()=>document.querySelector('#finale').classList.contains('on'));
});
await test('f','f-kitchen.html',async p=>{
 await p.locator('#btn-start').click();await p.locator('#bagItem').press('Enter');await p.locator('#jarItem').press('Enter');await p.locator('#sifter').waitFor();for(let i=0;i<6;i++)await p.locator('#sifter').press('Enter');await p.locator('#doughK').waitFor();for(let i=0;i<9;i++)await p.locator('#doughK').press('Space');await p.locator('#coverBtn').click();await p.locator('#pinch').waitFor();await p.locator('#pinch').press('Enter');await p.locator('#handsIcon').press('Enter');await p.locator('#c1').waitFor();await p.locator('#c1').press('Enter');await p.locator('#c2').press('Enter');await p.locator('#braidBtn').waitFor();for(let i=0;i<7;i++)await p.locator('#braidBtn').click();await p.locator('#challahE').waitFor();for(let i=0;i<13;i++)await p.locator('#challahE').press('Space');await p.locator('#trayItem').waitFor();await p.locator('#trayItem').press('Enter');await p.locator('#closeDoorBtn').click();await p.locator('#challahFinal').waitFor();await p.locator('#challahFinal').press('Enter');await p.locator('#coverBtn2').click();await p.waitForTimeout(850);assert((await p.locator('#end-score').innerText()).includes('500'));
 await p.locator('#btn-again').click();await p.locator('#kitchenMenu').click();await p.waitForLoadState();assert(await p.locator('.controlbar button').isVisible());await p.locator('.controlbar button').click();assert(await p.locator('#bagItem').isVisible());
});
await test('g','g-detective.html',async p=>{const answers=await p.evaluate(()=>CONTENT.witnesses.map(w=>w.true));for(let i=0;i<4;i++){await p.locator(`[data-clue="${i}"]`).click();await p.locator(`[data-decision="${answers[i]}"]`).click();await p.locator('#close').click()}await p.locator('#solve').click();assert(await p.evaluate(()=>data.won));await p.locator('#close').click();await p.reload();assert((await p.locator('#score').innerText()).includes('500'))});
await test('h','h-card-studio.html',async p=>{await p.locator('#signature').fill('משפחת ישראלי');await p.locator('[data-sticker="0"]').click();await p.locator('#cardPreview').click();assert(await p.locator('dialog img').isVisible());await p.locator('#closeCardPreview').click();const before=await p.evaluate(()=>data.stickers.length);await p.locator('#removeSticker').click();assert.equal(await p.evaluate(()=>data.stickers.length),before-1);await p.locator('#undo').click();assert.equal(await p.evaluate(()=>data.stickers.length),before);const dl=p.waitForEvent('download');await p.locator('#download').click();await(await dl).saveAs(path.join(out,'verified-card.png'));await p.reload();assert.equal(await p.locator('#signature').inputValue(),'משפחת ישראלי')});
await test('i','i-first-steps/index.html',async p=>{await p.locator('#fName').fill('בדיקת שמירה');await p.locator('#startBtn').click();const dl=p.waitForEvent('download');await p.locator('#iExport').click();const f=path.join(out,'test-backup.json');await(await dl).saveAs(f);const data=JSON.parse(fs.readFileSync(f,'utf8'));assert.equal(data.data.profile.name,'בדיקת שמירה');await p.locator('#iFile').setInputFiles(f);await p.waitForTimeout(700);assert(await p.locator('#iExport').isVisible())});
await test('j','j-meravach.html',async p=>{await p.locator('.mood-btn').first().click();const controls=await p.locator('#cardBox button').evaluateAll(es=>es.map(e=>({id:e.id,text:e.textContent})));fs.writeFileSync(path.join(out,'j-controls.json'),JSON.stringify(controls));const saved=p.locator('#save');if(await saved.count())await saved.click();await p.reload();assert(await p.locator('#cardBox').isVisible());await p.locator('[data-g=album]').click();const dl=p.waitForEvent('download');await p.locator('#s-album>.btn').click();await(await dl).saveAs(path.join(out,'test-notebook.txt'))});
await browser.close();if(results.some(r=>!r.passed))process.exitCode=1;
})();
